# Generated by Django 3.1.5 on 2021-01-09 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import learning_models.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='название')),
                ('model_file', models.FileField(null=True, upload_to=learning_models.models.user_directory_path)),
                ('fields', jsonfield.fields.JSONField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Обученная модель',
                'verbose_name_plural': 'Обученные модели',
                'ordering': ['user'],
            },
        ),
    ]
